
ARG IMAGE="mcr.microsoft.com/devcontainers/universal"
ARG VARIANT="2"

######################################
## Base image
## Installing dependencies
######################################
FROM ${IMAGE}:${VARIANT} AS base_image
